from pytube import Playlist

videos = ["https://www.youtube.com/watch?v=1fQbZqDsLho&index=3&list=PLgbI0QcBNn5jrD9cCezyQi6urwtxWPLbc",
"https://www.youtube.com/watch?v=EAYT_uJXxUE&list=PLgbI0QcBNn5jrD9cCezyQi6urwtxWPLbc&index=4",
"https://www.youtube.com/watch?v=BOSUi4Nx5YE&list=PLgbI0QcBNn5jrD9cCezyQi6urwtxWPLbc&index=6",
"https://www.youtube.com/watch?v=zm8Md4cojmw&index=7&list=PLgbI0QcBNn5jrD9cCezyQi6urwtxWPLbc",
"https://www.youtube.com/watch?v=TQllMMjIDaY&list=PLgbI0QcBNn5jrD9cCezyQi6urwtxWPLbc&index=8",
"https://www.youtube.com/watch?v=Vtl9oejuIKs&index=9&list=PLgbI0QcBNn5jrD9cCezyQi6urwtxWPLbc",
"https://www.youtube.com/watch?v=9sa5t8A2vug&list=PLgbI0QcBNn5jrD9cCezyQi6urwtxWPLbc&index=10",
"https://www.youtube.com/watch?v=sQMrS8M6BNs&index=11&list=PLgbI0QcBNn5jrD9cCezyQi6urwtxWPLbc",
"https://www.youtube.com/watch?v=Bv8KLPC4L70&list=PLgbI0QcBNn5grpFchkDRbB02NdfFxzAje",
"https://www.youtube.com/watch?v=vG0S3gHe9Iw&index=2&list=PLgbI0QcBNn5grpFchkDRbB02NdfFxzAje",
"https://www.youtube.com/watch?v=0oUaPgasyo8&list=PLgbI0QcBNn5grpFchkDRbB02NdfFxzAje&index=3",
"https://www.youtube.com/watch?v=mxZeF5ZNpig&index=4&list=PLgbI0QcBNn5grpFchkDRbB02NdfFxzAje",
"https://www.youtube.com/watch?v=EzJ8ttElRxI&index=5&list=PLgbI0QcBNn5grpFchkDRbB02NdfFxzAje",
"https://www.youtube.com/watch?v=PZoYPGbQCbY&index=6&list=PLgbI0QcBNn5grpFchkDRbB02NdfFxzAje",
"https://www.youtube.com/watch?v=8VfeAShG1zo&index=7&list=PLgbI0QcBNn5grpFchkDRbB02NdfFxzAje",
"https://www.youtube.com/watch?v=5uK2xF6iGc0&list=PLgbI0QcBNn5grpFchkDRbB02NdfFxzAje&index=8",
"https://www.youtube.com/watch?v=2k-Q_rHb0Rw&index=12&list=PLgbI0QcBNn5grpFchkDRbB02NdfFxzAje",
"https://www.youtube.com/watch?v=hVbgXshGqaA&index=13&list=PLgbI0QcBNn5grpFchkDRbB02NdfFxzAje",
"https://www.youtube.com/watch?v=2poEJFghOCs&list=PLgbI0QcBNn5grpFchkDRbB02NdfFxzAje&index=14",
"https://www.youtube.com/watch?v=gdPBqVOX-fY&index=16&list=PLgbI0QcBNn5grpFchkDRbB02NdfFxzAje",
"https://www.youtube.com/watch?v=wBuwWH8c0DY",
"https://www.youtube.com/watch?v=0bbgHTdSPJ4",
"https://www.youtube.com/watch?v=Le-3MIBxQTw",
"https://www.youtube.com/watch?v=aUpXO_9gyrc&index=2&list=RDLe-3MIBxQTw",
"https://www.youtube.com/watch?v=AI6nIJ-anYQ&index=3&list=RDLe-3MIBxQTw",
"https://www.youtube.com/watch?v=B9FzVhw8_bY&index=14&list=RDLe-3MIBxQTw",
"https://www.youtube.com/watch?v=MTrKkqE9p1o&list=RDLe-3MIBxQTw&index=17",
"https://www.youtube.com/watch?v=nOubjLM9Cbc&list=RDLe-3MIBxQTw&index=18",
"https://www.youtube.com/watch?v=faG8RiaANek&list=RDLe-3MIBxQTw&index=19",
"https://www.youtube.com/watch?v=x_ZeDn-hHGE&list=RDLe-3MIBxQTw&index=20",
"https://www.youtube.com/watch?v=zfaOf70M4xs&list=RDLe-3MIBxQTw&index=48",
"https://www.youtube.com/watch?v=yBdTVmSVq14&list=RDLe-3MIBxQTw&index=31",
"https://www.youtube.com/watch?v=Q0oIoR9mLwc&list=RDLe-3MIBxQTw&index=32",
"https://www.youtube.com/watch?v=YlUKcNNmywk&start_radio=1&list=RDEMf5I_WGknwqULRz9t7aGnjw",
"https://www.youtube.com/watch?v=g68lTTh3rmE&list=PLFb3Y6r6pPBdKWCGbl31cwqsptudMHxb6",
"https://www.youtube.com/watch?v=-uSJLb8ZESo&list=PLFb3Y6r6pPBdKWCGbl31cwqsptudMHxb6&index=2",
"https://www.youtube.com/watch?v=5fBv1SYoCJ0&list=PLFb3Y6r6pPBdKWCGbl31cwqsptudMHxb6&index=3",
"https://www.youtube.com/watch?v=pD2zAAzXQ0U&index=4&list=PLFb3Y6r6pPBdKWCGbl31cwqsptudMHxb6",
"https://www.youtube.com/watch?v=h7S_qJGoVno&index=5&list=PLFb3Y6r6pPBdKWCGbl31cwqsptudMHxb6",
"https://www.youtube.com/watch?v=ghC52Gt9SW4&list=PLFb3Y6r6pPBdKWCGbl31cwqsptudMHxb6&index=6",
"https://www.youtube.com/watch?v=tHHW4yjgHH4&index=7&list=PLFb3Y6r6pPBdKWCGbl31cwqsptudMHxb6",
"https://www.youtube.com/watch?v=pMtObets7_g&index=8&list=PLFb3Y6r6pPBdKWCGbl31cwqsptudMHxb6",
"https://www.youtube.com/watch?v=NKbhiM3KxRg&index=9&list=PLFb3Y6r6pPBdKWCGbl31cwqsptudMHxb6",
"https://www.youtube.com/watch?v=Wa_Ur3-Zra8&list=PLFb3Y6r6pPBdKWCGbl31cwqsptudMHxb6&index=10",
"https://www.youtube.com/watch?v=iQ0dR8ypDuw&list=PLFb3Y6r6pPBdKWCGbl31cwqsptudMHxb6&index=11",
"https://www.youtube.com/watch?v=NthLvAUJvDU",
"https://www.youtube.com/watch?v=HtUH9z_Oey8",
"https://www.youtube.com/watch?v=SyNt5zm3U_M&index=4&list=RDHtUH9z_Oey8",
"https://www.youtube.com/watch?v=yYvkICbTZIQ&index=10&list=RDHtUH9z_Oey8",
"https://www.youtube.com/watch?v=usNsCeOV4GM&list=RDHtUH9z_Oey8&index=11",
"https://www.youtube.com/watch?v=Qyclqo_AV2M&list=RDHtUH9z_Oey8&index=17",
"https://www.youtube.com/watch?v=UelDrZ1aFeY&index=23&list=RDHtUH9z_Oey8",
"https://www.youtube.com/watch?v=8qJTJNfzvr8&list=RDHtUH9z_Oey8&index=39",
"https://www.youtube.com/watch?v=n2MtEsrcTTs&list=RDHtUH9z_Oey8&index=38",
"https://www.youtube.com/watch?v=Eh44QPT1mPE",
"https://www.youtube.com/watch?v=UQmHHttYX0U&index=3&list=RDEMgIOBXzbTtzoAIqfUzIEziQ",
"https://www.youtube.com/watch?v=n4nFsByPTx4",
"https://www.youtube.com/watch?v=ojHBWT3H6qg",
"https://www.youtube.com/watch?v=HnlmdbnCF7U",
"https://www.youtube.com/watch?v=Moxt4JfITCY",
"https://www.youtube.com/watch?v=PRh1fBG5DPo"]


for x in videos:
    pl = Playlist(x)
    pl.download_all()

#pl = Playlist("https://www.youtube.com/playlist?list=PLgbI0QcBNn5jrD9cCezyQi6urwtxWPLbc")

#pl.download_all()
